
name: Go
on: [push, pull_request]
env:
  SRC_PATHS: ./api ./funcs ./reflection ./sinks ./sources ./operators ./stream ./testutil
  SRC_PATHS_PATTERN: ./api/... ./funcs ./reflection ./sinks/ ./sources/ ./operators/... ./stream ./testutil

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
        id: go

      - name: Tidy up
        run: |
          go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          skip-go-installation: true
          args: ./...

      - name: Code sanity
        run: |
          go vet $SRC_PATHS_PATTERN
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run tests
        run: |
          go test -v -race ./...