
name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go

      - name: Code checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test -v ./api ./collectors/ ./emitters ./operators/... ./stream ./testutil/ ./util/
      - name: Build
        run: |
          go build ./api ./collectors/ ./emitters ./operators/... ./stream ./testutil/ ./util/